language: python
install: "make"
script:
  - make ci
cache: pip
jobs:
  include:
    - stage: test
      python: '3.6'
      script:
        - python3 -m pip install pipenv && pipenv install && pipenv install --dev && pipenv shell && pytest
